<a href="https://colab.research.google.com/github/pammyyAnn/Activity_17/blob/main/Activity17Pam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
filename = '/content/drive/MyDrive/FINAL_ACT1_PAM/pll-team-stats.csv'
df = pd.read_csv(filename)
df.head()

,season,team,wins,losses,scores_for,scores_against,score_differential,one_point_goals,two_point_goals,assists,...,save_percentage,penalties,penalty_minutes,power_play_pecentage,power_play_goals,power_play_shots,x2_point_goals_allowed,penalty_kill_pecentage,penalty_kills,playoff_notes
0,2019,Chaos,7,3,130,128,2,106,12,67,...,0.555,33,18.0,0.478,11,8,3,0.690,20 - 29,Lost Semifinals
1,2019,Whipsnakes,6,4,125,116,9,101,12,71,...,0.550,24,13.0,0.263,5,7,7,0.636,14 - 22,Won Final
2,2019,Atlas,5,5,125,132,-7,109,8,73,...,0.534,42,27.0,0.435,10,9,10,0.700,21 - 30,Lost Quarterfinals
3,2019,Redwoods,5,5,116,117,-1,112,2,61,...,0.522,19,28.0,0.353,12,20,10,0.643,9 - 14,Lost Final
4,2019,Archers,5,5,112,106,6,100,6,67,...,0.555,24,16.0,0.519,14,9,5,0.714,15 - 21,Missed Playoffs

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   season                   29 non-null     int64
 1   team                     29 non-null     object
 2   wins                     29 non-null     int64
 3   losses                   29 non-null     int64
 4   scores_for               29 non-null     int64
 5   scores_against           29 non-null     int64
 6   score_differential       29 non-null     int64
 7   one_point_goals          29 non-null     int64
 8   two_point_goals          29 non-null     int64
 9   assists                  29 non-null     int64
 10  shots                    29 non-null     int64
 11  shot_percentage          29 non-null     float64
 12  x2_point_shots           29 non-null     int64
 13  x2_point_shot_pecentage  29 non-null     float64
 14  shots_on_goal            29 non-null     int64
 15  shots_on_goal_pecentage  29 non-null     float64
 16  turnovers                29 non-null     int64
 17  caused_turnovers         29 non-null     int64
 18  groundballs              29 non-null     int64
 19  faceoff_pecentage        29 non-null     float64
 20  faceoffs_won             29 non-null     int64
 21  faceoffs_lost            29 non-null     int64
 22  saves                    29 non-null     int64
 23  save_percentage          29 non-null     float64
 24  penalties                29 non-null     int64
 25  penalty_minutes          29 non-null     float64
 26  power_play_pecentage     29 non-null     float64
 27  power_play_goals         29 non-null     int64
 28  power_play_shots         29 non-null     int64
 29  x2_point_goals_allowed   29 non-null     int64
 30  penalty_kill_pecentage   29 non-null     float64
 31  penalty_kills            29 non-null     object
 32  playoff_notes            29 non-null     object
dtypes: float64(8), int64(22), object(3)
memory usage: 7.6+ KB

In [ ]:
df.describe().round(2)

,season,wins,losses,scores_for,scores_against,score_differential,one_point_goals,two_point_goals,assists,shots,...,faceoffs_lost,saves,save_percentage,penalties,penalty_minutes,power_play_pecentage,power_play_goals,power_play_shots,x2_point_goals_allowed,penalty_kill_pecentage
count,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,...,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00
mean,2020.62,4.14,4.14,102.83,102.86,-0.03,90.21,6.31,54.62,345.52,...,112.52,112.86,0.54,21.52,17.22,0.38,6.97,16.48,6.31,0.63
std,1.12,2.17,2.17,25.93,26.34,14.65,23.61,3.32,15.38,81.25,...,34.42,27.02,0.04,7.47,7.04,0.13,3.32,7.06,2.69,0.10
min,2019.00,0.00,0.00,46.00,51.00,-29.00,37.00,1.00,22.00,186.00,...,45.00,57.00,0.43,10.00,8.00,0.13,3.00,7.00,2.00,0.40
25%,2020.00,2.00,3.00,92.00,95.00,-10.00,78.00,4.00,47.00,306.00,...,93.00,97.00,0.52,15.00,13.00,0.29,4.00,9.00,5.00,0.57
50%,2021.00,5.00,4.00,111.00,108.00,-1.00,98.00,6.00,56.00,371.00,...,112.00,119.00,0.54,22.00,16.00,0.39,7.00,17.00,6.00,0.64
75%,2022.00,6.00,5.00,120.00,120.00,9.00,107.00,8.00,67.00,402.00,...,137.00,132.00,0.56,25.00,21.00,0.45,10.00,22.00,8.00,0.71
max,2022.00,9.00,9.00,130.00,140.00,31.00,116.00,13.00,75.00,442.00,...,167.00,156.00,0.63,42.00,38.00,0.67,14.00,35.00,12.00,0.81

In [ ]:
df['wins'].mean()

4.137931034482759

In [ ]:
df.groupby('team')['wins'].mean()

team
Archers       4.75
Atlas         4.50
Cannons       2.00
Chaos         3.25
Chrome        3.50
Redwoods      4.00
Waterdogs     4.00
Whipsnakes    6.00
Name: wins, dtype: float64

In [ ]:
df.groupby(['team', 'playoff_notes'])['wins'].mean()

team        playoff_notes
Archers     Lost Quarterfinals    5.0
            Lost Semifinals       4.5
            Missed Playoffs       5.0
Atlas       Lost Quarterfinals    4.0
            Lost Semifinals       6.0
Cannons     Lost Quarterfinals    3.0
            Missed Playoffs       1.0
Chaos       Lost Final            1.0
            Lost Semifinals       7.0
            Won Final             4.0
Chrome      Lost Quarterfinals    5.0
            Missed Playoffs       2.0
Redwoods    Lost Final            5.0
            Lost Quarterfinals    4.5
            Lost Semifinals       2.0
Waterdogs   Lost Quarterfinals    1.0
            Lost Semifinals       6.0
            Won Final             5.0
Whipsnakes  Lost Final            5.0
            Lost Semifinals       9.0
            Won Final             5.0
Name: wins, dtype: float64